#!/bin/sh
# You need to be root (sudo su) or have sudo access to execute this script
# This script will create  a new user's account in a linux server
echo "Please enter the userName for the account you want to create!"
read userName
echo "The user's name you entered is: "  $userName
sudo useradd $userName
echo "$userName user account created successfully"
echo "Set the password for $userName"
sudo passwd $userName

----

# read-user2.sh
# You need to be root or have sudo access to execute
echo -n "Enter the username: "
read username
echo -n "Enter the password: "
read -s password
sudo adduser "$username"
echo "$password" | sudo passwd "$username" --stdin
<<ST
--stdin
      This option is used to indicate that passwd should read the new
      password from standard input, which can be a pipe.
cat /etc/passwd to verify
ST
